### PR TITLE
Fix for various pathing issues

### PR DESCRIPTION
**Pull request by tobywisener**
-Fixed clicking objects to exit combat (previously MovementQueue was being cancelled every tick)
-Fixed cancelling out of WalkToObject tasks by clicking another square (previously player would still jump the ditch but in the wrong position)
-Fixed following players
-Fixed player bots following players
-Fixed follow dancing and improved the dance radius to be 1:1 with OSRS 

Dancing

### CODE REVIEW

**Comment by syuil** [comment]
So far only bug I found:
https://streamable.com/ameq3m

Spam clicking on something object, player, etc. while frozen with auto retaliate on will make your player look at the object while doing the attack but not facing the other player in combat (although projectile will go towards the other player)

**Comment by syuil** [comment]
Another bug only on ice-barrage:
https://streamable.com/fogwtx -- spams wild difference issue

**Comment by syuil** [comment]
On auto-cast - we run toward the player in 1 tile.

https://streamable.com/m5gdil

**Comment by syuil** [comment]
went into combat with mage-> fought -> left combat -> put melee -> went to attack bot-> got this error logged me

java.util.NoSuchElementException: No value present
    at java.base/java.util.Optional.get(Optional.java:143)
    at com.elvarg.game.model.movement.path.PathFinder.pathClosestAttackableTile(PathFinder.java:112)
    at com.elvarg.game.model.movement.MovementQueue.processCombatFollowing(MovementQueue.java:570)
    at com.elvarg.game.model.movement.MovementQueue.process(MovementQueue.java:262)
    at com.elvarg.game.entity.impl.player.Player.process(Player.java:405)
    at com.elvarg.game.World$1.execute(World.java:141)
    at com.elvarg.game.entity.updating.sync.GameSyncExecutor.sync(GameSyncExecutor.java:55)
    at com.elvarg.game.World.process(World.java:136)
    at com.elvarg.game.GameEngine.run(GameEngine.java:34)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
[World] Deregistering player - [username, host] : [Mike3, 127.0.0.1]



https://streamable.com/0g8zpz

**Comment by syuil** [comment]
Ran some tests -- everything looks great! Awesome fixes 🗡️ 

Some things I noticed:
Bot/Player still picks the other player as a target even after the player has left wild (sometimes) It'll just look at you and follow you with their eyes LOL: https://streamable.com/0p4rnc

---
Also, just found another -- if the bot is ranging and another bot walks in front of me he will stop attacking until the bot walks out of the way (only happened when bot is on the horizontal axis with a cbow, diagonal attacks worked fine. -- Hard to test this one.

**Comment by tobywisener** [comment]
> So far only bug I found: https://streamable.com/ameq3m
> 
> Spam clicking on something object, player, etc. while frozen with auto retaliate on will make your player look at the object while doing the attack but not facing the other player in combat (although projectile will go towards the other player)

Fixed :)

> On auto-cast - we run toward the player in 1 tile.
> 
> https://streamable.com/m5gdil

Fixed :)

All other issues should be fixed too, maybe except projectile thing

**Comment by syuil** [comment]
Small bugs:
1. if on same tile you will dance until the player moves and you will attack once he leaves the sq: https://streamable.com/qef9a2 
2. If you're in combat and click "follow" on another player you're player will constantly reset animation to try and follow the other player -- this will also run to find and follow the other player after death. The following doesn't seem to get reset for combat if auto-retaliate is on.

**Review by syuil — APPROVED** [review]

**Review by syuil — APPROVED** [review]

**Review by syuil — APPROVED** [review]

**Pull request merged**
